npmRegistryServer: "https://registry.npm.taobao.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

packageExtensions:
  postcss-loader@*:
    dependencies:
      "tailwindcss": "^3.0.11"
      